
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://matthewjdegarmo.com"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: "/"

# Google tracking id

google-tracking-id: "UA-187900687-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Matthew DeGarmo"
title: "{ matthewjdegarmo }"
description: "Blog and website of Matthew DeGarmo, blogging mainly about PowerShell. Opinions expressed are mine."
keywords: "degarmo, matthew, powershell, windows, tech"
favicon: "/img/posh_favicon.ico"

################
# Header layout #
################

black-favicon: "/img/pwsh/favicon-32x32.png"
#logo:  # leave blank if you don't want a logo
logo: "matthewjdegarmo.github.io/img/pwsh/posh_girl_closeup.png" # leave blank if you don't want a logo

background-img: "/img/posh_girl-bg_blur.jpg"
#background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 2200
lines: # You can add HTML Tags in the Text
  - text: "Who has time? But then if we do not ever take time, how can we ever have time? -The Merovingian"
  - text: "Give them quality. That's the best kind of advertising. -Milton Hershey"
  - text: "The value of an idea lies in the using of it. -Thomas Edison"
  - text: "A person who never made a mistake never tried anything new. -Albert Einstein"
  - text: "The way to get started is to quit talking and begin doing. -Walt Disney"
  - text: "In my defense, I was left unsupervised. -Lee St. John"


# me-img: "/img/jetpacktocat.png"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

me-img: "https://github.com/matthewjdegarmo.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/posh_girl_36p.png"
icon-48p: "/img/web-app/posh_girl_48p.png"
icon-72p: "/img/web-app/posh_girl_72p.png"
icon-96p: "/img/web-app/posh_girl_96p.png"
icon-144p: "/img/web-app/posh_girl_144p.png"
icon-192p: "/img/web-app/posh_girl_192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 50

paginate: 10

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "matthewjdegarmo"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/PowerShell_Core_6.0_icon.png"
    date: "January 2016"
    description: "Started coding / learning PowerShell!"
  - image: "/img/timeline/CompTIA_Security_2Bce.png"
    date: "February 2016"
    description: Became [CompTIA Security+ CE](https://www.youracclaim.com/badges/9d9de611-b326-4f2c-9716-e274ef446eb2){:target="_blank"} Certified.
  - image: "/img/timeline/icon-bachelor.png"
    date: "May 2016"
    description: "Graduated with a Bachelor's in Computer Information Systems: Networking"
  - image: "/img/timeline/isc2_cissp2.png"
    date: "March 2020"
    description: Became [CISSP](https://www.youracclaim.com/badges/013a3e80-685a-4f38-b382-081ca49610a7){:target="_blank"} Certified.
  - image: "/img/timeline/posh_girl_closeup.jpg"
    date: "June 2020"
    description: "Created Website and Blog!"
  - image: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
    date: "November 2020"
    description: "First merged PR on [PowerShell/PowerShell](https://github.com/PowerShell/PowerShell/pull/14113)"
  - image: "/img/timeline/twitch_icon_146123.png"
    date: "January 2021"
    description: "Started Live-Streaming PowerShell on [Twitch](https://twitch.tv/TechDufus)"
  - image: "/img/timeline/colorful_discord_icon.png"
    date: "April 2021"
    description: "Became a Moderator for a [PowerShell Discord Community](https://discord.gg/Z4PZCWKBGN)."
  - image: "/img/timeline/1st-twitch.jpg"
    date: "November 2021"
    description: "Gained Twitch Affiliate status."

# First image of the Timeline

timeline-img: "/img/timeline/Squidward_Future.jpg"

###########
# Contact #
###########

email:  # Leaving blank.


# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Matthew DeGarmo is an awesome person. He is a daily learner and nerd. A husband, and a father of 2, he likes long walks on the beach, and eating ice cream in his spare time."
author_blurb_image: "/img/author_matthewjdegarmo.png"

##################
# Social Buttons #
##################

social:
  - title: "twitch"
    url: "https://twitch.tv/TechDufus"
  - title: "facebook"
    url: "https://www.facebook.com/matthewjdegarmo"
  - title: "twitter"
    url: "https://twitter.com/matthewjdegarmo"
  - title: "github"
    url: "https://github.com/matthewjdegarmo"
  - title: "linkedin"
    url: "https://linkedin.com/in/matthewjdegarmo"
  - title: "reddit"
    url: "https://www.reddit.com/user/matthewjdegarmo"
  - title: "coffee"
    url: "https://buymeacoffee.com/matthewjdegarmo"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: 
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
