
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://TechDufus.com"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: "/"

# Google Analytics 4 tracking id (GA4)
# TODO: Replace G-XXXXXXXXXX with your actual GA4 measurement ID
google-tracking-id: "G-XXXXXXXXXX"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: true

#############
# HTML Head #
#############

lang: "en"
author: "TechDufus"
title: "{ TechDufus }"
description: "DevOps Engineer sharing insights on Kubernetes, Docker, PowerShell, and modern infrastructure. Building scalable solutions and sharing the journey."
keywords: "techdufus, powershell, windows, tech, linux, neovim, hardware, nerd."
favicon: "/img/favicon32x32.png"

################
# Header layout #
################

black-favicon: "/img/favicon32x32.png"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: true
shuffle: true # Shuffle the lines.
loop: true
loop-count: false # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 2200
lines: # You can add HTML Tags in the Text
  - text: "Who has time? But then if we do not ever take time, how can we ever have time? -The Merovingian"
  - text: "Give them quality. That's the best kind of advertising. -Milton Hershey"
  - text: "The value of an idea lies in the using of it. -Thomas Edison"
  - text: "A person who never made a mistake never tried anything new. -Albert Einstein"
  - text: "The way to get started is to quit talking and begin doing. -Walt Disney"
  - text: "In my defense, I was left unsupervised. -Lee St. John"
  - text: "I use Neovimᵇᵗʷ -TechDufus"


me-img: "https://www.gravatar.com/avatar/0bbf5d7c13901bd5a2f4e2a6d53e0476?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: true

# Icons for Web App mode

icon-36p: "/img/web-app/posh_girl_36p.png"
icon-48p: "/img/web-app/posh_girl_48p.png"
icon-72p: "/img/web-app/posh_girl_72p.png"
icon-96p: "/img/web-app/posh_girl_96p.png"
icon-144p: "/img/web-app/posh_girl_144p.png"
icon-192p: "/img/web-app/posh_girl_192p.png"

########
# Blog #
########

enable-gesture-navigation: true

post-preview-words: 60

paginate: 10

email-share: true
fb-share: true
twitter-share: true
linkedin-share: true
reddit-share: true
tumblr-share: true
pinterest-share: true
pocket-share: true
vkontakte-share: true

disqus-shortname: "matthewjdegarmo"

syntax-highlight: true

############
# Timeline #
############

events:
  - image: "/img/timeline/PowerShell_Core_6.0_icon.png"
    date: "January 2016"
    description: "Started coding / learning PowerShell!"
  - image: "/img/timeline/CompTIA_Security_2Bce.png"
    date: "February 2016"
    description: Became [CompTIA Security+ CE](https://www.youracclaim.com/badges/9d9de611-b326-4f2c-9716-e274ef446eb2){:target="_blank"} Certified.
  - image: "/img/timeline/icon-bachelor.png"
    date: "May 2016"
    description: "Graduated with a Bachelor's in Computer Information Systems: Networking"
  - image: "/img/timeline/isc2_cissp2.png"
    date: "March 2020"
    description: Became [CISSP](https://www.youracclaim.com/badges/013a3e80-685a-4f38-b382-081ca49610a7){:target="_blank"} Certified.
  - image: "/img/timeline/posh_girl_closeup.jpg"
    date: "June 2020"
    description: "Created Website and Blog!"
  - image: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
    date: "November 2020"
    description: "First merged PR on [PowerShell/PowerShell](https://github.com/PowerShell/PowerShell/pull/14113)"
  - image: "/img/timeline/twitch_icon_146123.png"
    date: "January 2021"
    description: "Started Live-Streaming PowerShell on [Twitch](https://twitch.tv/TechDufus)"
  - image: "/img/timeline/colorful_discord_icon.png"
    date: "April 2021"
    description: "Became a Moderator for a [PowerShell Discord Community](https://discord.gg/Z4PZCWKBGN)."
  - image: "/img/timeline/1st-twitch.jpg"
    date: "November 2021"
    description: "Became [Twitch Affiliate](https://www.twitch.tv/products/techdufus)."
  - image: "/img/timeline/runonflux.png"
    date: "July 2022"
    description: "Joined the [RunOnFlux](https://runonflux.io) Team."
  - image: "/img/timeline/raft-logo.png"
    date: "September 2024"
    description: "Joined [Raft](https://teamraft.com) as a DevOps Engineer, entering the defense contracting space to support mission-critical infrastructure and national security initiatives."

# First image of the Timeline

timeline-img: "/img/timeline/Squidward_Future.jpg"

###########
# Contact #
###########

email: hey@techdufus.com


# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: false

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "The Dufus is an awesome person. He is a daily learner and nerd. A husband, and a father of 4, he likes long walks on the beach, and eating ice cream in his spare time."
author_blurb_image: "https://www.gravatar.com/avatar/0bbf5d7c13901bd5a2f4e2a6d53e0476?s=500"

##################
# Social Buttons #
##################

social:
  - title: "fa-brands fa-x-twitter"
    url: "https://x.com/TechDufus"
  - title: "fa-brands fa-youtube"
    url: "https://www.youtube.com/@techdufus"
  - title: "fa-brands fa-twitch"
    url: "https://twitch.tv/TechDufus"
  - title: "fa-brands fa-linkedin"
    url: "https://linkedin.com/in/techdufus"
  - title: "fa-brands fa-github"
    url: "https://github.com/TechDufus"
  - title: "fa-solid fa-tree"
    url: "https://linktr.ee/TechDufus"
  - title: "fa-brands fa-discord"
    url: "https://discord.gg/5M4hjfyRBj"
  - title: "fa-brands fa-reddit"
    url: "https://www.reddit.com/user/TechDufus"
  - title: "fa-solid fa-mug-saucer"
    url: "https://buymeacoffee.com/TechDufus"
  - title: "fa-solid fa-rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

# keybase-username: TechDufus
keybase-in-social: false
keybase-in-footer: false

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

collections:
  setup:
    output: true
    order:
      - Hardware.md
      - Software.md
      - Homelab.md

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Setup: 'setup-preview'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: [
  "LICENSE", 
  "README.md", 
  "CONTRIBUTING", 
  "CONTRIBUTORS", 
  "CLAUDE.md",
  "Gemfile",
  "Gemfile.lock",
  "docker-compose.yml",
  "scripts",
  "node_modules",
  "playwright-report",
  "test-results",
  "_config.dev.yml"
]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

plugins:
  - webrick
  - jekyll-paginate
  - jemoji
