version: "3"

services:
  jekyll:
    image: ruby:3.1-alpine
    ports:
      - "4000:4000"
      - "35729:35729"
    working_dir: /srv/jekyll
    command: sh -c "apk add --no-cache build-base && gem install bundler && bundle install && bundle exec jekyll serve --watch --host 0.0.0.0 --config _config.yml,_config.dev.yml --livereload --force_polling"
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
