name: Blog Queue Workflow
#Run every hour.
on:
  schedule:
  - cron: '0 10 * * 1'
  workflow_dispatch:

jobs:
  update-sponsors-section:
    name: Publish blog post from queue.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: matthewjdegarmo/blogqueue@main
        with:
          queue_path: ./.blogqueue
          destination_path: ./_posts/
          committer_username: ${{ secrets.GH_USER }}
          committer_email: ${{ secrets.GH_EMAIL }}
